#!/bin/bash

# Usage: publish-download-section [files]

RELEASEDIR=/var/www/downloads/nymea-app

if [ "$1" == "-r" ]; then
    shift
    RELEASEDIR=$1
    shift
fi


while [ "$1" != "" ]; do
    FILE=$1
    FILENAME=$(basename -- "$1")
    EXTENSION="${FILENAME##*.}"
    NAME="${FILENAME%.*}"

    echo "Processing file $1"
    echo "    name: ${NAME}"
    echo "    extension ${EXTENSION}"

    if [ "${EXTENSION}" == "exe" ]; then
        STATICNAME=nymea-app-win-installer-latest.exe
        echo "Releasing Windows build ${FILENAME} --> ${STATICNAME}"
    fi

    if [ "${EXTENSION}" == "dmg" ]; then
        STATICNAME=nymea-app-osx-bundle-latest.dmg
        echo "Releasing macOS build ${FILENAME} --> ${STATICNAME}"
    fi

    if [ "${EXTENSION}" == "apk" ]; then
        STATICNAME=nymea-app-android-latest.apk
        echo "Releasint Android build ${FILENAME} --> ${STATICNAME}"
    fi

    # Release if we have a candidate
    if [ ! -z ${STATICNAME} ]; then
        cp -v ${FILE} ${RELEASEDIR}

        rm ${RELEASEDIR}/${STATICNAME} -f
        ln -s ${RELEASEDIR}/${STATICNAME} ${RELEASEDIR}/${FILENAME}
    fi

    shift
done
