#!/bin/bash -ex

if [ "$3" == "" ]; then
  echo "usage: $0 <repo> <git branch> [true|false]"
  echo "true|false at the end indicates a dry run. Which means it'll do all the merging but without pushing back to git"
  exit 1
fi

REPO=$1
GIT_BRANCH=$2
DRY_RUN=$3

if [ "$DRY_RUN" != "false" ]; then
  DRY_RUN="true"
fi

REPO_NAME=`echo $REPO | cut -d ':' -f 2 | cut -d '.' -f 1 | cut -d '/' -f 2`

echo "Repo: $REPO, branch: $GIT_BRANCH, repo name: $REPO_NAME"

mkdir source_merge_$REPO_NAME
cd source_merge_$REPO_NAME

git clone $REPO
cd $REPO_NAME
set +e
git branch -a | grep origin/$GIT_BRANCH
RES=$?
set -e
if [ $RES -ne 0 ]; then
  echo "No such remote branch $GIT_BRANCH for repository $REPO."
  exit 1
fi

git merge origin/$GIT_BRANCH --no-edit

# Export paths to nymea repo so we can run make lupdate on plugins
export PATH="`pwd`/../../source_merge_nymea/nymea/tools/nymea-plugininfocompiler/:$PATH"
export CPATH="`pwd`/../../source_merge_nymea/nymea/libnymea/"
export LIBRARY_PATH="`pwd`/../../source_merge_nymea/nymea/"
export PKG_CONFIG_PATH="`pwd`/../../source_merge_nymea/nymea/libnymea/pkgconfig"
# External plugins require INCLUDEPATH/nymea/plugin.pri
cp `pwd`/../../source_merge_nymea/nymea/libnymea/devices/plugin.pri /usr/include/nymea/

set +e
qmake .
make qmake_all
make lupdate
RES=$?
set -e

if [ $RES -eq 0 ]; then
  git commit -a -m "Automatic translations update by Jenkins" || true
else
  echo "WARNING: Translations could not be updated, make lupdate failed"
fi

TAG=`dpkg-parsechangelog --show-field version`
echo "Tagging release with: $TAG"
git tag $TAG

if [ "$DRY_RUN" = "false" ]; then
  echo "Pushing merged code back to the repository"
  git push --follow-tags
else
  echo "DRY RUN. Not actually pushing back to github"
fi

cd ..
