#!/bin/bash -e

if [ "$2" == "" ]; then
  echo "usage: $0 <repo> <git branch>"
  exit 1
fi

REPO=$1
GIT_BRANCH=$2

REPO_NAME=`echo $REPO | cut -d ':' -f 2 | cut -d '.' -f 1 | cut -d '/' -f 2`

echo "Repo: $REPO, branch: $GIT_BRANCH, repo name: $REPO_NAME"

mkdir source_merge_$REPO_NAME
cd source_merge_$REPO_NAME

git clone $REPO
cd $REPO_NAME
set +e
git branch -a | grep origin/$GIT_BRANCH
RES=$?
set -e
if [ $RES -ne 0 ]; then
  echo "No such remote branch $GIT_BRANCH for repository $REPO."
  exit 1
fi

git merge origin/$GIT_BRANCH --no-edit

# Export paths to nymea repo so we can run make lupdate on plugins
export PATH="`pwd`/../../source_merge_nymea/nymea/libnymea/plugin:$PATH"
export CPATH="`pwd`/../../source_merge_nymea/nymea/libnymea/"
export LIBRARY_PATH="`pwd`/../../source_merge_nymea/nymea/"
export PKG_CONFIG_PATH="`pwd`/../../source_merge_nymea/nymea/libnymea/pkgconfig"
# External plugins require INCLUDEPATH/nymea/plugin.pri
cp `pwd`/../../source_merge_nymea/nymea/libnymea/plugin/plugin.pri /usr/include/nymea/

qmake .
make qmake_all
set +e
make lupdate
RES=$?
set -e
if [ $RES -eq 0 ]; then
  git commit -a -m "Automatic translations update by Jenkins" || true
else
  echo "WARNING: Translations could not be updated, make lupdate failed"
fi

echo "Pushing merged code back to the repository"
git push

cd ..
